on: push
name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory
        run: |
          sudo apt-get update
          apt-get install -y xz-utils devscripts cowbuilder git screen
