on: push
name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils devscripts cowbuilder git
          echo "ALLOWUNTRUSTED=yes" >> /etc/pbuilderrc
          ./debian/util.sh build-all build-all -cbullseye -mquicktest -aamd64
